# Generated by Django 3.1.2 on 2020-10-19 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author_image', models.ImageField(blank=True, upload_to='authors', verbose_name='authors image')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('book_image', models.ImageField(blank=True, upload_to='books', verbose_name='book image')),
                ('isbn_num', models.CharField(blank=True, max_length=30)),
                ('total_pages', models.PositiveIntegerField(blank=True, verbose_name='Total number of pages in book')),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Want to read', 'Not started'), ('Currently reading', 'Reading'), ('Completed reading', 'Completed')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('display_pic', models.ImageField(blank=True, upload_to='profiles', verbose_name='profile picture')),
                ('total_books', models.PositiveIntegerField(default=0, verbose_name='Total number of books for user')),
                ('curr_no_books', models.PositiveIntegerField(default=0, verbose_name='Number of books Currently reading')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_read', models.PositiveIntegerField(verbose_name='total number of pages read')),
                ('progress_date', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='books.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
