# Generated by Django 3.1.2 on 2020-10-19 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201019_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
