# Generated by Django 3.1.2 on 2020-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20201019_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='total_books',
            field=models.PositiveIntegerField(default=0, verbose_name='total books read'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_num',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
