# Generated by Django 3.1.2 on 2020-10-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20201022_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='curr_no_books',
        ),
    ]
